### ISSUE TITLE
Build error when using Ember >= 1.10

### ISSUE THREAD

**Issue by hlogmans** [ghempton/ember-script#53]
Just to notify others: a new Ember-cli project will use ember 1.10, and then ember build (or server) will fail with:

Cannot read property 'create' of undefined
TypeError: Cannot read property 'create' of undefined
    at Object.<anonymous> (/Users/hlogmans/development/SalEmberFrontend/node_modules/broccoli-ember-script/node_modules/ember-script/lib/nodes.js:636:30)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/hlogmans/development/SalEmberFrontend/node_modules/broccoli-ember-script/node_modules/ember-script/lib/helpers.js:10:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Setting bower ember version to 1.9.1 solves this problem.

**Comment by hlogmans** [comment]
I switched to https://github.com/kimroen/ember-cli-coffeescript, renamed all .em files to .coffee and now everything works fine with all the latest versions.

**Comment by edborden** [comment]
You are writing EmberScript in .coffee files and it's compiling correctly with that configuration?

**Comment by hlogmans** [comment]
Yep, I love coffeescript. I thought ember-script was a dialect of coffeescript but all my files (controllers etc) worked out of the box, even leaving the emberscript marker # (ember) in the code (I do not use that everywhere, so it probable is ignored).

**Comment by edborden** [comment]
This didn't work for me. Coffeescript doesn't recognize "~>"

**Comment by kolybasov** [comment]
@hlogmans if you still want to use EmberScript with Ember-cli I can propose temporary solution:

add it to package.json
```
"broccoli-ember-script": "git://github.com/kolybasov/broccoli-ember-script"
```

or
```
npm install kolybasov/broccoli-ember-script --save-dev
```

**Comment by edborden** [comment]
This worked great, as I cling to EmberScript until it sinks :)
